### ISSUE TITLE
'when a user adds an omniberk to a post, add 3 3berks, when a user adds a 3berk add 3 berks'

### ISSUE THREAD

**Issue by TheSkeward** [TheSkeward/omega-bot#106]
Issue created by hateiskawaii#2069.

**Comment by CharlesFrayne** [comment]
should be closed. conflicts with the desired behavior in https://github.com/TheSkeward/omega-bot/issues/105

**Comment by CharlesFrayne** [comment]
also I think this just isn't possible. AIUI even bots can only react with an emoji once.
