### ISSUE TITLE
DM anybody who says IQ in their first 300 messages discussing IQ as a new poster is not disallowed, but is linked to significant risk of getting banned. Maybe participate in some other discussions first

### ISSUE THREAD

**Issue by TheSkeward** [TheSkeward/omega-bot#191]
Issue created by CharlesF#0306.

**Comment by Gabrielle-George** [comment]
working on this:
- add a flag for every user canSayIQ
- if they say IQ and the flag is not set:
    - if they have less than 300 messages, PM them
    - if they have more than 300 messages, set the flag

This way, you won't have to do expensive "Get all messages from this user" queries when a user has a majillion messages in the server. Since the server has a lot of regulars this seems prudent

**Comment by TheSkeward** [comment]
These are good implementation thoughts but I think I actually don't want this feature, gonna close this as "won't fix"
