### ISSUE TITLE
Allow people to comment on existing issues

### ISSUE THREAD

**Issue by goelzma** [TheSkeward/omega-bot#29]
I tried to comment on an existing issue and was not allowed to.
![image](https://user-images.githubusercontent.com/59125231/97788724-47100a80-1bbb-11eb-98b2-a40237706bb4.png)

**Comment by TheSkeward** [comment]
as far as I can tell this is a github issue rather than an issue with this project: https://github.com/googleads/googleads-mobile-unity/issues/397
