### ISSUE TITLE
treat Scott same as scott because autocorrect 😦

### ISSUE THREAD

**Issue by TheSkeward** [TheSkeward/omega-bot#41]
Issue created by imoimo#8685.

**Comment by marthinwurer** [comment]
If there are no other case-sensitive commands, you could do `lower()` on the first parameter, if you're just doing string comparison. If you're doing argparse it might be a bit harder.

**Comment by TheSkeward** [comment]
Fixed! There's actually a case-insensitive flag in the api that defines the bot class, so after finding that I just set it True and done.
