### ISSUE TITLE
split message.content.lower() on incoming messages to solve the scunthorpe problem. Although that does run into some problems with phrases... figure this out

### ISSUE THREAD

**Issue by TheSkeward** [TheSkeward/omega-bot#67]
Issue created by TheSkeward#1111.

**Comment by a1phabeta** [comment]
#81 my pull request sort of solves this problem in a simplistic way, we could use this as a starting point

**Comment by TheSkeward** [comment]
Fixed! no more scunthorpe problem. watchwords that are a single word require a precise match. Watchwords that are a phrase are just searched as a substring of the message.
